### ISSUE TITLE
Consider another license for this project

### ISSUE THREAD

**Issue by hansl** [bugadani/embedded-menu#18]
If I may suggest something, you should consider a real license for this project. WTFPL is a legal black hole (and lawyers will tend to avoid it), having worked with it in a corporate setting. In general it's considered "not recommended" (but the FSF no less).

MIT, ISC or BSD (Zero clause) are very WTFPL-adjacent.

Disclaimer: I just hate the WTFPL as it's basically license-less with extra steps.

**Comment by bugadani** [comment]
Sure I can think of something here. This project wasn't ever intended as anything serious, hence the wtfpl. Yes it's crude, but I just wanted something that is basically public domain.

I'll consider.
