### ISSUE TITLE
0.6 redesign / 🧠⛈️ing

### ISSUE THREAD

**Issue by bugadani** [bugadani/embedded-menu#36]
- [x] #35
 - [x] #38
 - [x] #39
 - [x] #40
 - [x] #41
 - [ ] Improve examples - they are very "thrown-together" right now
 - [ ] Try to resolve #14 - #42
 - [ ] Improve testing - unit tests, image comparison end-to-end tests

embedded-menu hasn't been a very serious project and so it looks like a pile of tech-debt. It's time to start changing that.

**Comment by bugadani** [comment]
cc @hansl in case you might have more ideas

**Comment by hansl** [comment]
> NI is a specialized version of Select.

Or the other way around ;) Something like this, maybe (taking from `simple.rs`)?

```rust
#[derive(Copy, Clone, Debug, PartialEq)]
enum Menu {
  Foo,
  CheckThis(usize, bool),
  TestEnum(usize),
}

// Not 100% sure about this one yet.
impl MenuMarker for Menu {
  fn marker(&self) -> &'static str {
    match self {
      Foo => ">",
      CheckThis(_, true) => "[X]",
      CheckThis(_, false) => "[ ]",
      TextEnum(0) => "A",
      TextEnum(1) => "AB",
      TextEnum(2) => "ABC",
    }
  }
}

// ... Rest of main here.

let menu = Menu::new("Some Menu")
  .with_input_handler(SdlInputAdapter::default())
  .add_item(NavigationItem::new("Foo", 1))
  .add_item(MenuItem::new("Check this 1", Menu::CheckThis(1, false)))
  .add_item(MenuItem::unselectable("===== Section =====")
  .add_item(MenuItem::new("Check this 2", Menu::CheckThis(2, false)))
  .add_item(MenuItem::new("Check this 3", Menu::CheckThis(3, false)))
  .build();

let action = `running: loop {
   let mut display: SimulatorDisplay<BinaryColor> = SimulatorDisplay::new(Size::new(128, 64));
   let mut sub = display.cropped(&Rectangle::new(Point::new(16, 16), Size::new(96, 34)));
   menu.update(&sub);
   menu.draw(&mut sub).unwrap();
   window.update(&display);

   for event in window.events() {
       if let Some(action) = menu.interact(event) {
           match action {
               Menu::Foo => break 'running action;
               Menu::CheckThis(i, b) => menu.selected_item().set_value(Menu::CheckThis(i, !b)),
               Menu::TestEnum(a) => menu.selected_item().set_value(Menu::TestEnum(a + 1 % 3)),
           }
       }
   }
};

eprintln!("Action selected: {action:?}");

// ... Rest of main here.

```

Just a first draft.

Some design considerations;

- Maybe interact could return a mut reference, or having a separate function on the item itself (`on_interact()`) to switch the values. `set_value()` is clunky.
- `selected_item()` vs `items().selected().first()` with `selected()` returning an iterator. That way we can do multi-selection down the line.

**Comment by bugadani** [comment]
I'll be honest, I'm not sure what you mean by multi-selection.

I'm somewhat uncomfortable with your idea of manually implementing the interaction logic of Select for everything. Same goes for `MenuMarker` which would get very annoying for bigger menus and reused selections. Though I do like that you made the `[ ]/[x]` user-configurable.

Current pre-caffeinated brain dump is:

 - Generalize `SelectionValue` as our "trait behind menu items". There's not much to do here, just rework the `next` function into an `interact(&mut self)`, probably, and maybe add a way to return the "marker" or printable value from it. Let's call this `MenuValue` for now.
 - Let's drop `NavigationItem`. They would be implemented with a `MenuValue` that does not change on interaction.
 - Let's drop `SectionTitle` and move its selectability property to the remaining internal menu item type. Ideally, their item type would be `!` or any other uninhabited enum and `interact` would just be an `unreachable!()` call; though I'm still not sure if we can make this work without adding a virtual variant to the R type.
 - Associate a container type to the Menu. This does nothing more than hold the different item values, so this is our `R`.
 - `add_item` can stay, but maybe for user-defined item types - maybe renamed to `add_general` or something.
 - `add_separator` / `add_item` / `add_unselectable` would all have the signature of `(item_title, item_value)`. Whether we want `item_value: impl Into<R>` for some simplicity is unclear as it doesn't work well if you have a menu with lots of similarly typed items.
 - I'm not yet sure what to do about slices of items.
 - I definitely want to move away from the lazy "Check this" in examples. It doesn't really show intended use well. I'm not sure if you want to get a number that shows you which checkbox you just checked, but I usually want something more... obvious, like its own enum variant.

Unfortunately I have some annoying issues elsewhere that I want to solve before coming back to this, but maybe by that time some of this crystallizes a bit better.

**Comment by hansl** [comment]
> I'll be honest, I'm not sure what you mean by multi-selection.

Just having the option to select multiple items at once and interact with all of them. I'm not sure after sleeping on it whether it's a need. It can be done with bool values already.

> Let's drop SectionTitle and move its selectability property to the remaining internal menu item type. Ideally, their item type would be ! or any other uninhabited enum and interact would just be an unreachable!() call; though I'm still not sure if we can make this work without adding a virtual variant to the R type.

`!` as a type is coming (see https://github.com/rust-lang/rust/issues/35121), and that would have been the one I pick but I didn't want to force nightly.

> I definitely want to move away from the lazy "Check this" in examples.

IMHO, there should be less examples and MORE MORE unit tests. But I'm not sure how unit tests (and maybe even screenshot tests) can be done with embedded-graphics for graphical libraries.

Agreed on the rest. I'm working on a `menu! {}` macro to help me simplify usage, as it gets kind of crazy to build, display, loop and manage menus. Having something like:

```rust
let value: SomeEnum = menu! {
    "Hello world" => { eprintln!("hello world!"); SomeEnum::Foo },
    "Check this!" SelectValue(false) => |v| { eprintln!("check this is {v}"); SomeEnum::Bar(v) },
    ----,
    ... other_items.slice() => |index| SomeEnum::Bazz(index),
    ----,
    "Custom Entry" "<Marker>" => SomeEnum::Foo,
};
```

No rush on this TBH.

**Comment by bugadani** [comment]
So what I've done to make menus a bit more ergonomic for me is:

 - [this trait](https://github.com/card-io-ecg/card-io-fw/blob/main/src/states/menu/mod.rs#L96-L155) that handles all the logic
 - and here's an [example](https://github.com/card-io-ecg/card-io-fw/blob/main/src/states/menu/display.rs)

Here I create a new struct for each menu. The `menu` trait method serves as a constructor, which is necessary for me because some of my menus may change in runtime so the constructor needs to be callable multiple times - I can't just set up one menu and call "do your work" on it.

The `fn display_menu` is the whole application state. It sets up and displays the menu, and saves the changed configuration on exit.

The exit condition is `handle_event` returning `Some` value (basically a new screen to transition to in my case).

While this isn't perfect and requires nightly, the end result is still quite all right. Your macro seems a bit more condensed, though also similarly quite complex.

---

We can add more tests for sure. We can even reuse examples as system tests with some image comparison in CI, I'm doing that in some other crates. The problem is mostly the animation part, but I guess we can deal with those pieces of code separately.

I'm not sure we want to test anything rendering-related in code. embedded-graphics can work with mock displays, but it's really fiddly to basically ASCII-art up an expectation.

I'm definitely in favour of integration-testing the interaction code, the scrolling had some regressions in the past that normally would have tests now if I spent the time to figure out how.

**Comment by bugadani** [comment]
Since I kinda ran out of steam here, I decided to release 0.6.0 as is so the past changes are available in a stable manner. Thanks for all your input and help!
